{
    "name": "Import RxH XML file",
    "author": "Erick Navarro <erick@navarro.io>",
    "category": "Localization",
    "license": "LGPL-3",
    "version": "0.1",
    "description": "Import Rxh from xml file generated by SUNAT and create a new supplier invoice",
    "depends": [
        "account",
    ],
    "data": [
        "wizard/import_rxh_views.xml",
    ],
    "application": True,
}
