{
    "name": "l10n PE Import RxH",
    "author": "Erick Navarro <erick@navarro.io>",
    "category": "Localization",
    "description": "Import Rxh from xml file generated by SUNAT and create a new supplier invoice",
    "depends": [
        "account",
    ],
    "data": [
        "wizard/import_rxh_views.xml",
    ],
    "application": True,
}
